spring.application.name=ChatKarlore

spring.datasource.url=JDBC:mysql://mysql:3306/chat_karo_re_app
spring.datasource.username=root
spring.datasource.password=Suraj@2027
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true